substitutions:
  _IMAGE_TAG: dev

steps:
  - id: build-runtime
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - services/runtime/Dockerfile
      - --tag
      - us-central1-docker.pkg.dev/$PROJECT_ID/veritas-preview-containers/runtime:${_IMAGE_TAG}
      - .
  - id: build-web
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/web/Dockerfile
      - --tag
      - us-central1-docker.pkg.dev/$PROJECT_ID/veritas-preview-containers/web:${_IMAGE_TAG}
      - .

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/veritas-preview-containers/runtime:${_IMAGE_TAG}
  - us-central1-docker.pkg.dev/$PROJECT_ID/veritas-preview-containers/web:${_IMAGE_TAG}

options:
  logging: CLOUD_LOGGING_ONLY
